### PR TITLE
Ensure on_locked_action is called when a lock is not acquired

### LINKED ISSUE #5: `on_locked_action` is not triggered if job is not `locked?` but `lock!` fails
When calling `enqueue`, `locked?` will check the existence of the key in Redis, and if it's not present will then call `lock!`

These two calls (`locked?` and `lock!`) are not atomic, so a lock could be acquired in the meantime, and the `lock!` would fail. However, in this case we're not calling the `on_locked_action` method

It sounds like we should, but maybe there are some implications that I haven't considered (ex: should we call `on_locked_action` if Redis is offline?). Thoughts?

### PR DESCRIPTION
**Pull request by wamaral**
The previous change on #3 fixed a race condition where a lock could be acquired more than once. When doing that, it started throwing exceptions when the lock could not be acquired, causing some noise.

It also did not fix the case where the `:on_locked_action` would not be called in that specific scenario - see #5 

This fix will ensure an exception is not thrown, and the `:on_locked_action` is properly called

Closes #5

### CODE REVIEW

File: lib/activejob/lockable/lockable.rb [hunk 1]
```diff
@@ -70,6 +64,11 @@ def lock_period
         options[:lock].to_i
       end
 
+      def trigger_on_locked_action
+        logger.info "Job is locked, expires in #{locked_ttl} second(s)"
+        send(on_locked_action) if on_locked_action && respond_to?(on_locked_action)
```
Comment (plcstevens) [inline lib/activejob/lockable/lockable.rb]: Could this be `public_send`, `send` makes me uneasy :(

**Review by plcstevens — CHANGES_REQUESTED** [review]

File: lib/activejob/lockable/lockable.rb (hunk 1 above)
Comment (wamaral) [reply lib/activejob/lockable/lockable.rb]: Sure thing! Done on 60cd0b6

**Review by plcstevens — APPROVED** [review]
